apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: USER_SERVICE_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@postgres:5432/user_db?sslmode=disable"
            - name: TOKEN_PRIVATE_KEY
              value: "0202fa3ed0e6861a49bd439d2a5bb0f0dac9eaf77aed5d92d748534a60d8d2037cba9be91bc76aa81cc4141a0d4ea71c63e0f8dd3f801fd7ca24806ad6ec4e57"
            - name: TCP_LISTENER_URL
              value: ":50051"
            - name: PRETTY_LOG
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
